export function buildRedirects(slugs) {
  const list = [];
  const add = (from, to) => list.push({ from, to, status: 301 });
  for (const slug of slugs) {
    add(`/projects/project-${slug}`, `/portfolio/${slug}`);
    add(`/projects/project-${slug}.html`, `/portfolio/${slug}`);
  }
  for (const page of ['about', 'portfolio', 'testimonials', 'contact']) add(`/${page}.html`, `/${page}`);
  add('/index', '/');
  add('/index.html', '/');
  add('/thankyou', '/thank-you');
  add('/thankyou.html', '/thank-you');
  add('/sitemap', '/sitemap-index.xml');
  add('/sitemap.xml', '/sitemap-index.xml');
  return list;
}

export function renderCloudflare(list) {
  const lines = ['# Generated by src/integrations/redirects.mjs. Do not edit.'];
  for (const r of list) {
    lines.push(`${r.from} ${r.to} ${r.status}`);
    lines.push(`${r.from}/ ${r.to} ${r.status}`);
  }
  return lines.join('\n') + '\n';
}

const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export function renderApache(list) {
  const lines = [
    '# Generated by src/integrations/redirects.mjs. Do not edit.',
    'Options -MultiViews',
    'ErrorDocument 404 /404.html',
    'RewriteEngine On',
    '',
  ];
  for (const r of list) lines.push(`RedirectMatch ${r.status} ^${escapeRegex(r.from)}/?$ ${r.to}`);
  lines.push(
    '',
    '# Redirect /page.html to /page',
    'RewriteCond %{THE_REQUEST} \\s/+(.+?)\\.html[\\s?] [NC]',
    'RewriteRule ^ /%1 [R=301,L,NE]',
    '',
    '# Serve /page from page.html',
    'RewriteCond %{REQUEST_FILENAME} !-d',
    'RewriteCond %{REQUEST_FILENAME} !-f',
    'RewriteCond %{REQUEST_FILENAME}.html -f',
    'RewriteRule ^(.+?)/?$ $1.html [L]',
  );
  return lines.join('\n') + '\n';
}
