export function buildRedirects(slugs) {
  const list = [];
  const add = (from, to) => list.push({ from, to, status: 301 });
  for (const slug of slugs) {
    add(`/projects/project-${slug}`, `/portfolio/${slug}`);
    add(`/projects/project-${slug}.html`, `/portfolio/${slug}`);
  }
  for (const page of ['about', 'portfolio', 'testimonials', 'contact']) add(`/${page}.html`, `/${page}`);
  add('/index', '/');
  add('/index.html', '/');
  add('/thankyou', '/thank-you');
  add('/thankyou.html', '/thank-you');
  add('/sitemap', '/sitemap-index.xml');
  add('/sitemap.xml', '/sitemap-index.xml');
  return list;
}

export function renderCloudflare(list) {
  const lines = ['# Generated by src/integrations/redirects.mjs. Do not edit.'];
  for (const r of list) {
    lines.push(`${r.from} ${r.to} ${r.status}`);
    lines.push(`${r.from}/ ${r.to} ${r.status}`);
  }
  return lines.join('\n') + '\n';
}

const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export function renderApache(list) {
  const lines = [
    '# Generated by src/integrations/redirects.mjs. Do not edit.',
    'Options -MultiViews -Indexes',
    // /portfolio is both portfolio.html and a portfolio/ folder; serve the page, not a folder redirect.
    'DirectorySlash Off',
    'ErrorDocument 404 /404.html',
    'RewriteEngine On',
    '',
    "# Act only on the visitor's request. Apache re-runs these rules after its own internal",
    '# rewrites (page.html lookups, the index file, the 404 page); redirecting those loops forever.',
    'RewriteCond %{ENV:REDIRECT_STATUS} !^$',
    'RewriteRule ^ - [L]',
    '',
    '# One canonical address: https, no www (live domain only, so local tests are unaffected)',
    'RewriteCond %{HTTP_HOST} ^(www\\.)?loftconcept\\.com\\.sg$ [NC]',
    'RewriteCond %{HTTPS} !=on [OR]',
    'RewriteCond %{HTTP_HOST} ^www\\. [NC]',
    'RewriteRule ^ https://loftconcept.com.sg%{REQUEST_URI} [R=301,L]',
    '',
    '# Legacy URLs',
  ];
  for (const r of list) lines.push(`RewriteRule ^${escapeRegex(r.from.slice(1))}/?$ ${r.to} [R=${r.status},L]`);
  lines.push(
    '',
    '# Any other /page.html or /page/ goes to /page',
    'RewriteRule ^(.+)\\.html/?$ /$1 [R=301,L]',
    'RewriteCond %{DOCUMENT_ROOT}/$1.html -f',
    'RewriteRule ^(.+)/$ /$1 [R=301,L]',
    '',
    '# Serve /page from page.html',
    'RewriteCond %{DOCUMENT_ROOT}/$1.html -f',
    'RewriteRule ^(.+)$ $1.html [L]',
  );
  return lines.join('\n') + '\n';
}
